services:
  bot:
    container_name: faber-bot
    build:
      context: .
      dockerfile: Dockerfile
    image: faber-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=$DISCORD_TOKEN
